{{- if .Values.operator.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - linstor.wedos.org
  resources:
  - linstorcontrollers
  - linstornodes
  - linstorstoragepools
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - linstor.wedos.org
  resources:
  - linstorcontrollers/status
  - linstornodes/status
  - linstorstoragepools/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "linstor.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - linstor-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - linstor.wedos.org
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "linstor.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ template "linstor.fullname" . }}-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "linstor.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "linstor.fullname" . }}-operator
  template:
    metadata:
      labels:
        name: {{ template "linstor.fullname" . }}-operator
    spec:
      containers:
      - args: [ '--max-workers={{ .Values.operator.workers }}' ]
        env:
        - name: LS_CONTROLLERS
          {{- if .Values.stunnel.enabled }}
          value: localhost:3370
          {{- else }}
          value: {{ template "linstor.fullname" . }}-controller:{{ .Values.controller.restApiBindPort }}
          {{- end }}
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: linstor-operator
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
        name: operator
      {{- if .Values.stunnel.enabled }}
      - args:
        - /etc/stunnel/stunnel-client.conf
        image: {{ .Values.stunnel.image.repository }}:{{ .Values.stunnel.image.tag }}
        imagePullPolicy: {{ .Values.stunnel.image.pullPolicy }}
        name: stunnel
        volumeMounts:
        - mountPath: /etc/stunnel
          name: stunnel-config
      {{- end }}
      imagePullSecrets:
{{ toYaml .Values.operator.image.pullSecrets | indent 8 }}
      serviceAccountName: {{ template "linstor.fullname" . }}-operator
{{- with .Values.operator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      {{- if .Values.stunnel.enabled }}
      volumes:
      - name: stunnel-config
        projected:
          sources:
          - configMap:
              name: {{ template "linstor.fullname" . }}-stunnel
          - secret:
              name: {{ template "linstor.fullname" . }}-stunnel
      {{- end }}
{{- end }}
